=== kruchenkov/training/Lab3/planes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/planes"
        xmlns:tns="http://www.example.org/planes" elementFormDefault="qualified">
    <element name="planes">
        <complexType>
            <sequence>
                <element name="plane" type="tns:Plane" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Plane">
        <sequence>
            <element name="model" type="string"/>
            <element name="origin" type="string"/>
            <element name="chars" type="tns:Chars"/>
            <element name="parameters">
                <complexType>
                    <sequence>
                        <element name="length" type="long"/>
                        <element name="width" type="long"/>
                        <element name="height" type="long"/>
                    </sequence>
                </complexType>
            </element>
            <element name="price" type="long"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>
    <complexType name="Chars">
        <sequence>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Support"/>
                        <enumeration value="Escort"/>
                        <enumeration value="Fighter"/>
                        <enumeration value="Interceptor"/>
                        <enumeration value="Scout"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="sits">
                <simpleType>
                    <restriction base="byte">
                        <minInclusive value="1"/>
                        <maxInclusive value="2"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="gun" minOccurs="0">
                <complexType>
                    <attribute name="caliber" type="string" use="required"/>
                </complexType>
            </element>
            <element name="air-to-air-missiles" type="byte" minOccurs="0" maxOccurs="20"/>
            <element name="air-to-ground-missiles" type="byte" minOccurs="0" maxOccurs="10"/>
            <element name="radar" type="boolean"/>
        </sequence>
    </complexType>

</schema>

=== kruchenkov/training/Lab3/planes.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.org/planes"
        xsi:schemaLocation="http://www.example.org/planes planes.xsd">
    <plane id="ID-1">
        <model>F-150</model>
        <origin>France</origin>
        <chars>
            <type>Fighter</type>
            <sits>2</sits>
            <gun>"7.56mm"</gun>
            <airtoairmissiles>20</airtoairmissiles>
            <airtogroundmissiles>10</airtogroundmissiles>
            <radar>true</radar>
        </chars>
        <parameters>
            <length>123123</length>
            <width>123123</width>
            <height>1231231</height>
        </parameters>
        <price>12331</price>
    </plane>
    <plane id="ID-2">
        <model>F-140</model>
        <origin>America</origin>
        <chars>
            <type>Interceptor</type>
            <sits>2</sits>
            <gun>"7.56mm"</gun>
            <airtoairmissiles>20</airtoairmissiles>
            <airtogroundmissiles>10</airtogroundmissiles>
            <radar>false</radar>
        </chars>
        <parameters>
            <length>123</length>
            <width>21312</width>
            <height>2311</height>
        </parameters>
        <price>123122</price>
    </plane>
</planes>
